---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Style/RedundantRegexpEscape:
  Exclude:
  - app/models/user_email_extra_preferences.rb
Style/RedundantStringEscape:
  Exclude:
  - lib/notifyme/html/base.rb
Style/SafeNavigation:
  Exclude:
  - lib/notifyme/git/old_new_branch.rb
  - lib/notifyme/patches/repository_patch.rb
Style/SlicingWithRange:
  Exclude:
  - lib/notifyme/telegram_bot/command_factory.rb
Style/StringConcatenation:
  Exclude:
  - lib/notifyme/events/time_entry/base.rb
  - lib/notifyme/hooks/add_assets.rb
  - spec/lib/notifyme/notify_spec.rb
Style/SuperWithArgsParentheses:
  Exclude:
  - app/helpers/notifyme_mailer_helper.rb
